### ISSUE TITLE
Intent.Modelers.Eventing 4.0.2 breaks backward compatibility with Intent Architect v3.4.x

### ISSUE THREAD

**Issue by stephanjohnson** [IntentSoftware/Support#2]
When creating a new Clean Architecture application with the MassTransit integration modules installed, the resulting module restoration warns of a compatibility issue.

![image](https://user-images.githubusercontent.com/6469385/232200168-6c227bf7-12e1-4833-8774-a92598685110.png)

> Module Intent.Modelers.Eventing 4.0.2 with supported client version(s) of \[4.0.0-beta.4, 5.0.0) is not compatible with this version (3.4.4) of Intent Architect

This issue was created by creating a new Clean Architecture project using Intent Architect v3.4.4.

**Comment by JonathanLydall** [comment]
Thanks @stephanjohnson, we updated the Application Template and `supportedClientVersions` on Friday as appropriate so that this issue should not occur.
